### ISSUE TITLE
Potential Additions?

### ISSUE THREAD

**Issue by dnkennedy** [smweis/methods_in_neuro#1]
Thanks for creating this resource.

I see in twitter (well, X) that ReproNim has been mentioned. You can contact me if you need any assistance parceing any of the ReproNim materials.

I also wanted to make sure to mention NITRC (NITRC.org). First, it is a general clearinghouse of many resources that can be useful.  More specifically, pursuant to the categories that you've broken your listing out into, the NITRC Computational Environment (NITRC-CE; https://www.nitrc.org/ce/) might fall under your "Computational/coding based resources" section; and the NITRC Image Repository (NITRC-IR; https://www.nitrc.org/xnat/index.php) might fall under your "Dataset resources".

Anyway, just wanted to mention this. Happy to discuss further if you want.

**Comment by smweis** [comment]
Added both - and thank you for the offer!! I've never used any of these, so might reach out if we decide to!
